config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'

  post '/update_stream', to: 'api/v1/streams#update_stream'

  resources :users, only: [:show] do
    resources :chat_messages, only: [:create]
  end

  direct :thumbnail do |model|
    "#{request.protocol}#{request.host}:20080/app/#{model.handle}/thumb.jpg"
  end

  direct :stream do |model|
    "ws://#{request.host}:3333/app/#{model.handle}/webrtc"
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
# frozen_string_literal: true

class ChatMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User', inverse_of: :sent_chat_messages,
                      dependent: :destroy
  belongs_to :receiver, class_name: 'User', inverse_of: :received_chat_messages,
                        dependent: :destroy

  validates :body, presence: true

  after_create_commit do
    broadcast_prepend_to(receiver,
                         :messages,
                         target: :messages,
                         partial: 'users/message',
                         locals: { message: self })
  end
end

app/models/stream_configuration.rb
# frozen_string_literal: true

class StreamConfiguration
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :title, :string, default: 'Stream Name'
end

app/models/stream_configuration_type.rb
# frozen_string_literal: true

class StreamConfigurationType < ActiveRecord::Type::Value
  def type
    :json
  end

  def cast_value(value)
    case value
    when String
      decoded = begin
        ActiveSupport::JSON.decode(value)
      rescue StandardError
        nil
      end
      StreamConfiguration.new(decoded) unless decoded.nil?
    when Hash
      StreamConfiguration.new(value)
    when StreamConfiguration
      value
    else
      raise(ActiveRecord::SerializationTypeMismatch,
            "Attribute was supposed to be a StreamConfiguration, but was a #{value.class}. -- #{value.inspect}")
    end
  end

  def serialize(value)
    case value
    when Hash, StreamConfiguration
      ActiveSupport::JSON.encode(value)
    else
      super
    end
  end

  def changed_in_place?(raw_old_value, new_value)
    cast_value(raw_old_value) != new_value
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :sent_chat_messages, class_name: 'ChatMessage', foreign_key: :sender_id, inverse_of: :sender,
                                dependent: :destroy
  has_many :received_chat_messages, class_name: 'ChatMessage', foreign_key: :receiver_id, inverse_of: :receiver,
                                    dependent: :destroy

  enum status: { offline: 0, online: 1, streaming: 2 }
  attribute :stream_configuration, StreamConfigurationType.new

  validates :first_name, :last_name, :handle, presence: true

  before_create -> { self.stream_key = SecureRandom.hex(16) }

  def full_name
    "#{first_name} #{last_name}"
  end

  after_commit :update_streams_list, on: %i[create update]

  private

  def update_streams_list
    if offline?
      broadcast_remove_to('streams')
      return
    end
    if streaming?
      broadcast_append_to('streams', target: 'streams', partial: 'home/stream', locals: { stream: self })
    end
  end
end

app/controllers/api/application_api_controller.rb
# frozen_string_literal: true

class Api::ApplicationApiController < ActionController::API
end

app/controllers/api/v1/streams_controller.rb
# frozen_string_literal: true

class Api::V1::StreamsController < Api::ApplicationApiController
  before_action :find_user

  UPDATE_PATHS = {
    'opening' => ->(user) { user.streaming! },
    'closing' => ->(user) { user.offline! }
  }.freeze

  def update_stream
    unless UPDATE_PATHS.key?(request_params[:status])
      Rails.logger.info("Action not found: #{request_params[:status]}")
      render(json: { message: 'Action not found' }, status: :not_found) && return
    end

    UPDATE_PATHS[request_params[:status]].call(@user)

    Rails.logger.info("Routing to: #{stream_url}")
    render(json: { allowed: true, new_url: stream_url }, status: :ok)
  end

  private

  def request_params
    params[:request]
  end

  def stream_url
    @_stream_url ||= begin
      incoming_url = URI::parse(request_params[:url].to_s)
      incoming_url.path = ['', 'app', @user.handle].join('/')
      incoming_url.scheme = 'rtmp'
      incoming_url.to_s
    end
  end

  def find_user
    key = URI::parse(request_params[:url].to_s).path.split('/').last
    @user = User.find_by!(stream_key: key)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name handle])
  end
end

app/controllers/chat_messages_controller.rb
# frozen_string_literal: true

class ChatMessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    ChatMessage.create!(chat_message_params)
  end

  private

  def chat_message_params
    {
      sender_id: User.last.id,
      receiver_id: params[:user_id],
      body: params[:body]
    }
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @broadcasting_users = User.streaming
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def show
    @messages = @user.received_chat_messages.order(created_at: :desc).preload(:sender).limit(20)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_stream.html.erb
<div class="s3" id="<%= dom_id(stream) %>">
  <%= link_to(stream, style: 'text-decoration: none; color: inherit;', data: { 'data-turbolinks': "false" }) do %>
    <div class="card">
      <div class="card-image">
        <div class='thumbnail' style='background-image: url("<%=thumbnail_url(stream) %>")'></div>
      </div>
      <div class="card-content">
        <span class="card-title"><%= stream.stream_configuration.title %></span>
        <p>@<%= stream.handle %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_streams.html.erb
<% streams.each do |stream| %>
  <%= render 'stream', stream: stream %>
<% end %>

app/views/home/index.html.erb
<%= turbo_stream_from('streams') %>

<div class="row" id="streams">

  <%= render "home/streams", streams: @broadcasting_users %>
</div>

<%= vite_stylesheet_tag 'home.scss' %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user.present? %>
          <li><span>Logged in as <%= current_user.email %></span></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RtmpStream</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script>
		  document.documentElement.setAttribute('theme', 'dark');
    </script>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_stylesheet_tag 'dark_theme.scss' %>
    <%= vite_stylesheet_tag 'application.scss' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <main>
      <div class='container'>
        <%= yield %>
      </div>
    </main>
    <% if current_user.present? %>
      <footer class='page-footer'>
        <div class='container'>
          <div class='row'>
            <div class='col s6 offset-s3'>
              Your stream key is <span><%= current_user.stream_key %></span>
            </div>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>

app/views/users/_message.html.erb
<div class="message">
  <div class="content">
    <span class="sender-handle"><%= message.sender.handle %>: </span>
    <span><%= message.body %></span>
  </div>
  <span class="timestamp"><%= message.created_at.strftime("%H:%M") %></span>
</div>

app/views/users/_messages.html.erb
<% messages.each do |message| %>
  <%= render 'message', message: message %>
<% end %>

app/views/users/show.html.erb
<%= content_for(:body_attributes, 'data-turbolinks=false') %>

<%= turbo_stream_from(@user, :messages) %>

<div class="row stream" data-controller="stream" data-stream-stream-url-value="<%= stream_url(@user) %>">
    <video class="col s11" id="video" controls crossorigin playsinline poster="<%= vite_asset_path('images/default_thumbnail.webp') %>"></video>
  <div class="col s1">
    <div class="chat right-align">
      <h6>Chat</h6>
      <div id="messages" class="messages <%= dom_id(@user) %>">
        <%= render 'messages', messages: @messages %>
      </div>
      <div class="write-message">
        <%= form_with url: user_chat_messages_path(@user), method: :post, id: 'message-form', data: { action: 'submit->stream#submit' } do |f| %>
          <div class="input-field">
            <%= f.text_field :body, required: true, data: { 'stream-target': 'message'}, disabled: current_user.blank? %>
            <%= f.label :body, current_user.blank? ? 'Log in to write a message' : 'Write your message'  %>
          </div>
          <%= f.submit 'Send', class: 'btn waves-effect', disabled: current_user.blank? %>
        <% end %>
      </div>
  </div>
</div>

</div>
<%= vite_stylesheet_tag 'stream.scss' %>